<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
        <PackageReference Include="Microsoft.Garnet" Version="1.0.84" />
    </ItemGroup>

</Project>
