name: CI Build

on:
  push:
    branches: [ 'main' ]
    paths-ignore: [ '.github/**' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: '0'
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./test/CacheService.UnitTests --no-restore
    - name: Test
      run: dotnet test ./test/CacheService.UnitTests --no-build --verbosity normal
